2021-07-01 09:20:32,881 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
202021-07-01 09:20:32,890 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc82021-07-01 09:20:32,968 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:32,974 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 89, 39, 25, -4, 26, 62, 18, 27, 1418, 15, 74, 5, 1225, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,040 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,042 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 79, 26, 26, -3, 36, 64, 12, 28, 1448, 16, 116, 6, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,082 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,088 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [109, 84, 34, 29, -3, 38, 54, 16, 29, 1372, 20, 60, 4, 2425, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,140 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,141 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [127, 99, 46, 19, -4, 27, 46, 20, 30, 1402, 17, 102, 6, 1075, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,184 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,186 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [85, 96, 36, 16, -5, 29, 50, 12, 30, 1462, 17, 68, 5, 1975, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,271 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,272 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 91, 29, 20, -2, 39, 48, 14, 27, 1492, 19, 110, 4, 1525, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,298 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,300 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [91, 86, 31, 17, -2, 32, 58, 14, 28, 1432, 16, 54, 4, 2125, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,391 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,392 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [73, 94, 44, 22, -5, 33, 60, 18, 28, 1478, 18, 88, 5, 1825, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,442 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,454 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [103, 81, 41, 28, -4, 35, 56, 16, 29, 1388, 14, 82, 5, 2275, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,505 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,506 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 79, 26, 26, -3, 36, 64, 12, 27, 1418, 15, 74, 5, 1225, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,535 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,537 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 89, 39, 25, -4, 26, 62, 18, 28, 1448, 16, 116, 6, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,584 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,585 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [127, 99, 46, 19, -4, 27, 46, 17, 30, 1402, 17, 154, 6, 2859, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,634 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,641 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [85, 96, 36, 16, -5, 35, 51, 12, 30, 1469, 17, 68, 5, 1975, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,690 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,691 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [103, 81, 40, 28, -4, 36, 64, 12, 27, 1418, 15, 74, 5, 1225, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,735 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,738 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 79, 26, 26, -3, 35, 56, 16, 29, 1388, 14, 82, 5, 2275, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,780 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,783 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 89, 39, 25, -4, 26, 62, 18, 29, 1448, 16, 116, 6, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,827 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,829 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [109, 84, 34, 29, -3, 38, 54, 16, 28, 1372, 20, 60, 4, 2425, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,862 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,865 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 91, 48, 20, -5, 39, 48, 14, 27, 1492, 14, 110, 4, 2125, 39980, 80, 1, 1, 1, 1]
2021-07-01 09:20:33,897 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,905 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [91, 86, 31, 17, -2, 32, 58, 14, 28, 1432, 16, 54, 4, 1525, 40455, 78, 1, 1, 1, 1]
2021-07-01 09:20:33,956 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:33,957 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [97, 76, 49, 23, -3, 30, 52, 19, 29, 1358, 18, 96, 6, 1675, 41000, 79, 1, 1, 1, 1]
2021-07-01 09:20:34,018 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,019 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 89, 39, 25, -3, 35, 56, 16, 29, 1388, 14, 82, 5, 2275, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,110 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,119 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 79, 26, 26, -4, 26, 62, 18, 29, 1448, 16, 116, 6, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,166 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,168 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [85, 96, 36, 16, -5, 39, 48, 14, 27, 1492, 14, 110, 4, 2125, 39980, 80, 1, 1, 1, 1]
2021-07-01 09:20:34,191 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,193 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 91, 48, 20, -5, 35, 51, 12, 30, 1469, 17, 68, 5, 1975, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,258 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,260 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [97, 76, 49, 23, -3, 30, 51, 12, 30, 1469, 17, 68, 5, 1975, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,306 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,310 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 91, 48, 20, -5, 35, 52, 19, 29, 1358, 18, 96, 6, 1675, 41000, 79, 1, 1, 1, 1]
2021-07-01 09:20:34,347 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,353 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [91, 86, 31, 17, -2, 32, 58, 14, 28, 1432, 16, 88, 5, 1825, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,399 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,400 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [73, 94, 44, 22, -5, 33, 60, 18, 28, 1478, 18, 54, 4, 1525, 40455, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,461 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,462 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [81, 81, 40, 28, -4, 35, 56, 16, 29, 1354, 14, 82, 5, 1225, 41779, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,492 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,499 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 89, 39, 25, -3, 36, 64, 12, 27, 1418, 15, 74, 5, 2275, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,588 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,591 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 79, 26, 26, -2, 26, 62, 18, 29, 1448, 16, 172, 6, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,626 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,628 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [127, 99, 41, 26, -4, 27, 46, 17, 30, 1402, 22, 216, 6, 2859, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,670 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,670 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [85, 96, 36, 18, -5, 39, 48, 14, 30, 1492, 14, 110, 4, 3335, 39980, 79, 1, 1, 1, 1]
2021-07-01 09:20:34,719 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,720 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [97, 76, 49, 23, -3, 30, 51, 12, 30, 1469, 14, 110, 4, 1975, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,761 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,768 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [95, 96, 36, 29, -3, 39, 48, 22, 30, 1492, 17, 140, 6, 3335, 39980, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,831 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,837 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 91, 48, 20, -5, 35, 52, 19, 29, 1398, 18, 96, 6, 3176, 41592, 79, 1, 1, 1, 1]
2021-07-01 09:20:34,889 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,890 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [73, 94, 44, 22, -4, 35, 62, 16, 29, 1354, 14, 54, 4, 1525, 41881, 78, 1, 1, 1, 1]
2021-07-01 09:20:34,951 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:34,956 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [81, 81, 40, 28, -5, 33, 60, 18, 28, 1478, 18, 82, 5, 1225, 41779, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,024 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,026 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 79, 26, 26, -2, 26, 62, 12, 27, 1418, 15, 74, 5, 2275, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,126 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,129 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 89, 39, 25, -3, 36, 64, 18, 29, 1448, 16, 172, 6, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,190 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,193 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [97, 76, 49, 23, -3, 30, 46, 17, 30, 1469, 14, 110, 4, 1975, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,227 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,233 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [127, 99, 41, 26, -4, 27, 51, 12, 30, 1402, 22, 216, 6, 2859, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,272 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,273 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [95, 96, 36, 29, -3, 39, 48, 22, 30, 1492, 17, 140, 6, 3335, 39980, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,341 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,342 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 89, 39, 25, -3, 36, 64, 18, 29, 1448, 16, 172, 4, 1375, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,400 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,401 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [97, 76, 49, 23, -3, 36, 46, 19, 27, 1469, 14, 110, 4, 2092, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,443 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,451 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [127, 99, 41, 26, -3, 39, 48, 22, 30, 1492, 17, 140, 6, 3335, 39980, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,507 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,508 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [95, 96, 36, 29, -4, 27, 51, 12, 30, 1402, 22, 216, 6, 2859, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,567 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,568 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [73, 94, 44, 28, -5, 33, 62, 16, 29, 1354, 14, 54, 4, 1525, 41881, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,676 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,686 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [81, 81, 40, 22, -4, 35, 60, 18, 28, 1478, 18, 82, 5, 1225, 41779, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,750 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,757 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [121, 107, 38, 25, -3, 36, 64, 18, 29, 1448, 16, 172, 4, 1375, 40246, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,827 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,831 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 107, 38, 25, -3, 36, 64, 18, 29, 1426, 16, 172, 5, 1375, 40246, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,871 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,872 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [109, 84, 33, 29, -3, 38, 54, 16, 29, 1372, 20, 181, 4, 2425, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:35,935 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,940 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [95, 91, 48, 20, -5, 35, 52, 19, 29, 1398, 18, 96, 6, 3176, 41592, 79, 1, 1, 1, 1]
2021-07-01 09:20:35,986 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:35,988 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 96, 36, 29, -4, 27, 51, 12, 30, 1402, 22, 216, 6, 2859, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:36,046 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:36,049 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 96, 36, 29, -2, 32, 51, 12, 30, 1402, 22, 216, 6, 2859, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:36,082 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:36,088 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [91, 86, 31, 17, -4, 27, 58, 14, 28, 1432, 16, 88, 5, 1825, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:36,130 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:36,133 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [73, 94, 44, 28, -4, 35, 60, 16, 29, 1354, 14, 54, 4, 1525, 41881, 78, 1, 1, 1, 1]
2021-07-01 09:20:36,172 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:36,174 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [81, 81, 40, 22, -5, 33, 62, 18, 28, 1478, 18, 82, 5, 1225, 41779, 78, 1, 1, 1, 1]
2021-07-01 09:20:36,217 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:36,218 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [79, 107, 38, 25, -3, 26, 62, 12, 27, 1418, 15, 74, 5, 2275, 41000, 78, 1, 1, 1, 1]
2021-07-01 09:20:36,252 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - ---- Start aircraft sizing module ----
2021-07-01 09:20:36,256 - c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check     - INFO - Current individual vairables: [115, 79, 26, 26, -2, 36, 64, 18, 29, 1426, 16, 172, 5, 1375, 40246, 78, 1, 1, 1, 1]
es\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,380 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.088950
2021-07-01 09:20:33,381 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,381 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,393 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,396 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,398 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,398 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,403 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,417 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.034985
2021-07-01 09:20:33,419 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,427 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,456 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,459 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,463 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,464 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,466 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,472 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.039978
2021-07-01 09:20:33,472 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,486 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,506 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,510 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,516 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,519 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,520 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,524 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.029984
2021-07-01 09:20:33,525 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,526 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,539 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,549 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,557 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,559 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,562 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,568 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.041489
2021-07-01 09:20:33,570 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,573 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,587 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,594 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,598 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,602 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,609 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,616 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.039972
2021-07-01 09:20:33,618 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,620 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,643 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,652 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,657 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,660 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,665 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,670 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.048972
2021-07-01 09:20:33,672 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,681 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,693 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,700 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,703 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,705 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,712 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,720 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.037980
2021-07-01 09:20:33,722 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,723 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,740 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,745 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,748 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,749 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,750 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,760 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.034982
2021-07-01 09:20:33,762 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,767 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,786 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,790 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,796 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,798 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,799 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,805 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.033975
2021-07-01 09:20:33,806 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,807 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,830 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,833 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,835 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,836 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,837 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,846 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.037977
2021-07-01 09:20:33,847 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,848 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,867 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,869 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,871 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,872 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,874 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,880 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.031983
2021-07-01 09:20:33,881 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,884 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,907 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,912 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,916 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,917 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,918 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,928 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.040968
2021-07-01 09:20:33,935 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:33,946 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:33,959 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:33,969 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:33,976 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:33,979 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:33,981 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:33,989 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.039503
2021-07-01 09:20:33,999 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,005 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,021 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,024 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,028 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,067 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,077 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,088 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.079957
2021-07-01 09:20:34,090 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,091 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,123 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,132 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,134 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,137 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,138 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,149 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.055971
2021-07-01 09:20:34,152 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,155 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,170 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,172 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,174 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,175 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,176 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,181 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.023986
2021-07-01 09:20:34,182 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,182 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,196 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,205 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,207 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,210 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,214 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,221 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.037980
2021-07-01 09:20:34,230 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,243 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,264 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,271 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,278 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,280 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,282 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,290 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.044973
2021-07-01 09:20:34,293 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,294 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,315 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,319 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,324 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,328 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,329 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,335 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.038978
2021-07-01 09:20:34,336 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,337 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,357 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,365 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,369 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,371 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,373 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,382 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.044065
2021-07-01 09:20:34,383 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,384 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,401 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,414 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,429 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,432 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,434 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,438 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.051969
2021-07-01 09:20:34,446 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,451 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,463 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,466 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,469 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,470 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,473 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,477 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.025023
2021-07-01 09:20:34,478 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,478 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,502 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,552 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,556 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,557 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,559 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,571 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.092101
2021-07-01 09:20:34,572 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,574 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,592 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,604 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,606 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,607 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,608 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,614 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.035008
2021-07-01 09:20:34,615 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,616 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,636 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,641 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,650 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,652 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,653 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,657 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.041079
2021-07-01 09:20:34,658 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,659 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,671 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,674 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,677 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,680 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,682 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,688 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.027978
2021-07-01 09:20:34,689 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,703 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,721 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,725 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,730 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,734 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,735 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,744 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.038066
2021-07-01 09:20:34,746 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,748 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,772 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,783 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,792 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,795 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,802 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,810 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.059494
2021-07-01 09:20:34,815 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,818 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,839 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,850 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,859 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,861 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,864 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,878 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.058970
2021-07-01 09:20:34,879 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,880 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,891 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,900 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,902 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,903 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,904 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:34,921 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.039978
2021-07-01 09:20:34,938 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:34,939 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:34,958 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:34,964 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:34,976 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:34,979 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:34,982 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,003 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.063978
2021-07-01 09:20:35,007 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,010 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,033 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,042 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,050 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,052 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,057 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,078 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.063472
2021-07-01 09:20:35,090 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,105 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,136 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,142 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,148 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,149 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,151 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,157 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.038488
2021-07-01 09:20:35,157 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,175 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,198 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,202 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,204 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,205 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,206 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,213 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.035981
2021-07-01 09:20:35,215 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,217 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,235 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,239 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,243 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,250 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,253 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,258 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.040978
2021-07-01 09:20:35,259 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,260 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,274 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,278 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,282 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,284 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,287 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,304 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.043975
2021-07-01 09:20:35,308 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,321 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,351 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,357 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,359 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,368 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,375 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,382 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.054486
2021-07-01 09:20:35,382 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,389 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,402 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,406 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,410 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,415 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,419 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,426 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.037111
2021-07-01 09:20:35,427 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,432 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,455 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,458 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,460 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,461 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,472 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,486 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.053119
2021-07-01 09:20:35,487 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,488 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,508 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,512 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,517 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,520 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,522 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,540 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.050973
2021-07-01 09:20:35,542 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,552 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,569 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,576 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,582 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,584 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,588 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,591 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.036978
2021-07-01 09:20:35,652 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,653 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,690 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,694 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,703 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,710 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,717 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,725 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.072089
2021-07-01 09:20:35,726 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,731 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,762 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,781 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,787 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,788 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,790 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,797 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.061962
2021-07-01 09:20:35,803 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,815 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,834 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,838 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,841 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,842 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,844 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,853 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.034980
2021-07-01 09:20:35,853 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,858 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,877 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,907 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,909 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,909 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,910 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,918 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.057854
2021-07-01 09:20:35,921 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,924 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,949 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,953 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:35,957 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:35,960 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:35,963 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:35,972 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.045490
2021-07-01 09:20:35,974 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:35,975 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:35,989 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:35,994 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,001 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,007 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,016 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,022 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.045974
2021-07-01 09:20:36,023 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:36,031 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:36,051 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:36,060 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,064 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,065 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,067 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,071 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.034974
2021-07-01 09:20:36,073 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:36,074 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:36,091 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:36,095 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,099 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,100 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,103 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,111 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.035980
2021-07-01 09:20:36,115 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:36,119 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:36,134 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:36,138 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,143 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,147 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,149 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,156 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.035490
2021-07-01 09:20:36,157 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:36,158 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:36,177 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:36,190 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,194 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,195 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,196 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,203 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.043973
2021-07-01 09:20:36,204 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:36,209 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:36,219 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:36,225 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,232 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,234 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,235 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,239 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.028982
2021-07-01 09:20:36,240 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
2021-07-01 09:20:36,240 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== Start network profit module ====
2021-07-01 09:20:36,258 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< airplane_sizing
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 81, in objective_function
    status, flags, vehicle = airplane_sizing(vehicle,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\airplane_sizing_check.py", line 205, in airplane_sizing
    vehicle = fuselage_cross_section(vehicle)
  File "c:\users\aarc8\documents\github\mdoairb\framework\Sizing\Geometry\fuselage_sizing.py", line 46, in fuselage_cross_section
    seat_cushion_width_YC = fuselage['seat_width']
KeyError: 'seat_width'
2021-07-01 09:20:36,261 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< objective_function
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment
2021-07-01 09:20:36,263 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Exception ocurred during calculations
2021-07-01 09:20:36,263 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Aircraft not passed sizing and checks, profit: 0
2021-07-01 09:20:36,267 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - ERROR - >>>>>>>>>> Error at <<<<<<<<<<<< write_bad_results
Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 92, in objective_function
    if status == 0:
UnboundLocalError: local variable 'status' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function.py", line 294, in objective_function
    write_bad_results(error,x)
  File "c:\users\aarc8\documents\github\mdoairb\framework\utilities\output.py", line 497, in write_bad_results
    with open(r'Database/Results/Aircrafts_with_error/acft_' + str(start_time) +'.txt','w') as output:
FileNotFoundError: [Errno 2] No such file or directory: 'Database/Results/Aircrafts_with_error/acft_2021-07-01-0920.txt'
2021-07-01 09:20:36,272 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - Network profit excecution time: 0:00:00.029982
2021-07-01 09:20:36,272 - c:\users\aarc8\documents\github\mdoairb\framework\Optimization\objective_function     - INFO - ==== End network profit module ====
